services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./backend/migrations:/app/migrations
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: issac
      POSTGRES_PASSWORD: isaacdbpass2024
      POSTGRES_DB: isaacdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test_db:
    image: postgres:13
    container_name: test_db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  test_postgres_data:
