"""Initial models

Revision ID: 9b11063293fe
Revises: 
Create Date: 2024-09-03 20:28:18.598116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b11063293fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itempools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itempools_id'), 'itempools', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('trinkets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trinkets_id'), 'trinkets', ['id'], unique=False)
    op.create_table('item_itempool',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('itempool_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['itempool_id'], ['itempools.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'itempool_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_itempool')
    op.drop_index(op.f('ix_trinkets_id'), table_name='trinkets')
    op.drop_table('trinkets')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_itempools_id'), table_name='itempools')
    op.drop_table('itempools')
    # ### end Alembic commands ###
