"""Add wiki_id to Trinket and Item models

Revision ID: e81a9e2ddbf7
Revises: 9b11063293fe
Create Date: 2024-10-06 20:19:30.376281

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e81a9e2ddbf7"
down_revision = "9b11063293fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("wiki_id", sa.String(), nullable=False))
    op.add_column("trinkets", sa.Column("wiki_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trinkets", "wiki_id")
    op.drop_column("items", "wiki_id")
    # ### end Alembic commands ###
